MONGODB_HOST: mongodb-{{ env }}.bharathgaveni.fun
REDIS_HOST: redis-{{ env }}.bharathgaveni.fun
CATALOGUE_HOST: catalogue-{{ env }}.bharathgaveni.fun
CART_HOST: cart-{{ env }}.bharathgaveni.fun
USER_HOST: user-{{ env }}.bharathgaveni.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.bharathgaveni.fun
MYSQL_HOST: mysql-{{ env }}.bharathgaveni.fun
SHIPPING_HOST: shipping-{{ env }}.bharathgaveni.fun
PAYMENT_HOST: payment-{{ env }}.bharathgaveni.fun