  - name: copying the mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb server
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: Allowing remote connections to mongodb
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0' 

  - name: mongodb service enable and start
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
