  - name: "disable default nginx"
    ansible.builtin.command: dnf module disable nginx -y

  - name: "enable nginx version:1.24"
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: "install nginx"
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove html directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/  

  - name: create html directory
    ansible.builtin.file:
      state: directory
      path: /usr/share/nginx/html/

  - name: remove frontend.zip file in temp directory
    ansible.builtin.file:
      state: absent
      path: /tmp/frontend.zip

  - name: "downloading the code in tmp directory of frontend file"    
    ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

  - name: unzipping the frontend code in tmp directory 
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /app
      remote_src: yes  

  - name: "delete the default nginx.conf file"
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: "copy nginx.conf"
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx 





