  - name: installing mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: starting the service and enable
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup for root password for mysql
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1