  - name: "remove app directory"
    ansible.builtin.file:
      path: /app
      state: absent

  - name: "Creating app directory"
    ansible.builtin.file:
      path: /app
      state: directory  
  
  - name: "remove/delete the {{ component }} zip file in tmp directory"
    ansible.builtin.file:
      path: /tmp/{{ component }}.zip
      state: absent

  - name: "dowloading the {{ component }} code in the tmp file location"
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
      dest: /tmp/{{ component }}.zip   


  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/{{ component }}.zip 
      dest: /app
      remote_src: yes    # Ansible tells to serach in remote machine not in ansible machine