  - name: "install maven which takecares java installation"
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql  

  - name: "install dependencies based on pom.xml"
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: "move jar file to /app dir from /target dir"
    ansible.builtin.command: mv target/{{ component }}-{{ version }}.jar {{ component }}.jar
    args:
      chdir: /app

