# $ANSIBLE_VAULT;1.1;AES256
# 64666266656436326139396462353837323831633536316230353262396532316563616337346532
# 6462383437313338363232653239653965633139306530390a376335346336386133376563626236
# 32613635316534396637363636623366636530353936626364326462393163373435323430346638
# 3430313232343635300a636666626439613335656561333763633332353763626436326531306234
# 65663061633537653234333539653966313933336139313764633237363539303036343739386133
# 3536373539663534306330653261666337326235353865626139
 MYSQL_ROOT_PASSWORD: msg="{{ lookup('amazon.aws.aws_ssm', '/roboshop/{{ env }}/mysql/mysql_root_password', region='us-east-1', decrypt=true ) }}"