$ANSIBLE_VAULT;1.1;AES256
39386335623934303039313865613734313932326461313937383761656363626438326236373162
3865643462366634313363303337303233316664343330630a313734396538343432353363366665
38313137303236613133306361663834386364356565623163343364613164653830633833386562
6561326138333237330a386332626232356362376565366637303830656365343634306166383064
61353538663332646133656462623435663636383034303166633862343135316536303961336262
3033303738336637326530646533306534623530393932623834
